spring:
  application:
    name: auth-service

  # Configuração do banco de dados para o ambiente Docker
  datasource:
    # Conecta ao contêiner 'auth-db' na porta interna 5432
    url: jdbc:postgresql://auth-db:5432/auth_service_db
    username: usuario_dev
    password: senha_dev
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: embedded

jwt:
  secret: 'wJk/dG8xH+aVbNpL6fRzV2yZ4sA7eFjQ5gU9hC3iKlE='

# A porta interna do contêiner, como definida no docker-compose
server:
  port: 9002