### Update an existing patient entity

PUT http://localhost:8080/api/v1/patients/713fd9a6-b1bf-44c7-9c09-01feeab190ee

Content-Type: application/json


{
  "name": "João da Silva",
  "email": "joao8.silva@email.com",
  "birthDate": "20-05-1988",
  "addressRequestDTO": {
    "street": "Avenida Sao paulo",
    "number": "123",
    "zipcode": "12345-678",
    "complement": "Apto 101",
    "neighborhood": "Centro",
    "city": "São Paulo",
    "state": "SP"
  }
}

###