version: '3.8'

services:
  patient-db:
    image: postgres:16-alpine
    container_name: patient-db
    ports:
      - "5435:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: usuario_dev
      POSTGRES_PASSWORD: senha_dev
      POSTGRES_DB: patient_db
    volumes:
      - patient_db_data:/var/lib/postgresql/data
    networks:
      - patient-network

  adminer:
    image: adminer:4.8.1
    container_name: patient-adminer
    restart: unless-stopped
    ports:
      - "8090:8080"
    networks:
      - patient-network
    profiles:
      - dev


  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      # Habilita o login anônimo para facilitar o desenvolvimento
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - patient-network

  kafka:
    image: docker.io/bitnami/kafka:3.6
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9099:9099" # Porta para sua aplicação no localhost
      - "9099:9099" # Porta para comunicação interna (e ferramentas)
    depends_on:
      - zookeeper
    environment:
      # Conexão com o Zookeeper
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181

      # --- CONFIGURAÇÃO DOS LISTENERS ---
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT

      #  Define os LISTENERS usando os NOMES definidos acima
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9099

      # Define os endereços ANUNCIADOS usando os NOMES
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9099

      # Define o listener para comunicação interna entre os brokers
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL

    networks:
      - patient-network


  auth-db:
    image: postgres:16-alpine
    container_name: auth-service-db
    ports:
      - "5436:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: usuario_dev
      POSTGRES_PASSWORD: senha_dev
      POSTGRES_DB: auth_service_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - patient-network


  # Simula a AWS
  localstack:
    container_name: "localstack-main"
    image: localstack/localstack:latest
    ports:
      # A porta "Edge" que direciona para todos os serviços
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=0
    volumes:
      # Volume para persistir os dados entre as reinicializações do contêiner
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - patient-network


volumes:
  auth_db_data:
  patient_db_data:
  localstack_data:

networks:
  patient-network:
    driver: bridge


