server:
  port: 8098

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Rota para o serviço de autenticação
            - id: auth-service-route
              uri: ${AUTH_SERVICE_URL} # Será injetado pelo CDK
              predicates:
                - Path=/api/v1/auth/**

                  # Rota para o serviço de usuários (que está no auth-service)
            - id: user-service-route
              uri: ${AUTH_SERVICE_URL} # Usa a mesma URL
              predicates:
                - Path=/api/v1/users/**

                  # Rota para o serviço de pacientes
            - id: patient-service-route
              uri: ${PATIENT_SERVICE_URL} # Será injetado pelo CDK
              predicates:
                - Path=/api/v1/patients/**
              filters:
                - StripPrefix=0
                      # O filtro JwtValidation vai usar a variável abaixo
                      # - JwtValidation

            # Propriedade para o filtro de validação de JWT
auth:
  service:
    url: ${AUTH_SERVICE_URL}