CREATE TABLE IF NOT EXISTS patients (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    address TEXT,
    birth_date DATE NOT NULL,
    registration_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP

);

ALTER TABLE patients
    DROP COLUMN IF EXISTS phone,
    DROP COLUMN IF EXISTS cpf;

ALTER TABLE patients
    DROP CONSTRAINT IF EXISTS chk_birth_date,
    DROP CONSTRAINT IF EXISTS chk_email_format;
