spring:
  application:
    name: billing-service
  rsocket:
    server:
      port: 6565  # Porta RSocket (TCP)

server:
  port: 8081  # Porta HTTP principal (para REST/Actuator)

grpc:
  server:
    port: 9091  # Porta gRPC
