# ===============================================================
# PERFIL DE CONFIGURAÇÃO PARA AMBIENTE DOCKER
# Ativado quando o perfil 'docker' está ativo.
# ===============================================================
spring:
  datasource:
    url: jdbc:postgresql://patient-db:5432/patient_db
    username: ${DB_USERNAME:usuario_dev}
    password: ${DB_PASSWORD:senha_dev}

  grpc:
    client:
      billing-service:
        address: static://billing-service:9092
        negotiationType: PLAINTEXT


  kafka:
    bootstrap-servers: kafka:9092

  jpa:
    hibernate:
      ddl-auto: validate # 'validate' é uma boa prática para não recriar o schema a cada reinicialização

# Mantém a porta do servidor, que já está mapeada no docker-compose
server:
  port: 8080