# PERFIL DE CONFIGURAÇÃO PARA AMBIENTE DOCKER
spring:
  datasource:
    url: jdbc:postgresql://patient-db:5432/patient_db
    username: ${DB_USERNAME:usuario_dev}
    password: ${DB_PASSWORD:senha_dev}

  kafka:
    bootstrap-servers: kafka:9092

  jpa:
    hibernate:
      ddl-auto: validate

grpc:
  client:
    billing-service:
      address: static://billing-service:9092
      negotiationType: PLAINTEXT

server:
  port: 8080