spring:
  application:
    name: patient-service

  datasource:
    # URL do banco de dados com valores padrão
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:patient_db}
    username: ${DB_USERNAME:usuario_dev}
    password: ${DB_PASSWORD:senha_dev}
    driver-class-name: org.postgresql.Driver
    # ... outras configurações de datasource

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: embedded

  # Configuração gRPC movida para a seção padrão com valores padrão
  grpc:
    client:
      billing-service:
        # Se a variável de ambiente não existir, usa localhost
        address: static://${BILLING_SERVICE_HOST:localhost}:${BILLING_SERVICE_PORT:9092}
        negotiationType: PLAINTEXT

server:
  port: 8080



