spring:
  application:
    name: patient-service

  datasource:
    url: jdbc:postgresql://localhost:5435/patient_db
    username: usuario_dev
    password: senha_dev
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: embedded

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5435/patient
    username: usuario_dev
    password: senha_dev

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://servidor-prod:5432/nome_do_banco_prod
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# http://localhost:8080/swagger-ui.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html

grpc:
  client:
    billing-service:
      address: static://billing-service:9091
      negotiationType: PLAINTEXT


